replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/gcp-test-472411/repo1/python-app
  tag: "@sha256:cc8d94f724483830405db33c6ee08e541fe33ed1c39ceab315854a74abace0c0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
